name: Convert Markdown to HTML

on:
  push:
    paths:
      - '**/*.md'

jobs:
  convert-markdown-to-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Find updated markdown files
      id: find_md_files
      run: |
        PREVIOUS_SHA=$(git log -n 2 --format=%H | tail -1)
        CURRENT_SHA=$(git log -n 1 --format=%H)
        git log -n 2 --format=%H
        echo "HERE1"
        git log -n 1 --format=%H
        echo "HERE2"
        echo "Previous commit SHA: $PREVIOUS_SHA"
        echo "Current commit SHA: $CURRENT_SHA"
        git log --format=%H
        echo "HERE3"
        MD_FILES=$(git diff --name-only $PREVIOUS_SHA $CURRENT_SHA | grep '\.md$')
        echo "Updated markdown files: $MD_FILES"
        echo "::set-output name=md_files::$MD_FILES"

    - name: Convert markdown to HTML
      if: steps.find_md_files.outputs.md_files != ''
      run: |
        for file in ${{ steps.find_md_files.outputs.md_files }}; do
          pandoc "$file" -o "${file%.md}.html"
        done

    - name: Commit and push HTML files
      if: steps.find_md_files.outputs.md_files != ''
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.html
        git commit -m 'Update HTML files from updated markdown'
        git push
